---
abstract: 'DEPRECATED -- use Dist::Zilla::Plugin::Git::NextVersion instead'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Dist::Zilla::Tester: 0
  File::Copy::Recursive: 0
  File::Find: 0
  File::Temp: 0
  File::pushd: 0
  Path::Class: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-BumpVersionFromGit
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dist::Zilla::Plugin::BumpVersionFromGit:
    file: lib/Dist/Zilla/Plugin/BumpVersionFromGit.pm
    version: 0.009
requires:
  Dist::Zilla: 4
  Dist::Zilla::Role::VersionProvider: 0
  Git::Wrapper: 0
  Moose: 0
  Version::Next: 0
  namespace::autoclean: 0.09
  perl: 5.006
  version: 0.80
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-BumpVersionFromGit
  homepage: http://github.com/dagolden/dist-zilla-plugin-bumpversionfromgit
  repository: http://github.com/dagolden/dist-zilla-plugin-bumpversionfromgit
version: 0.009
