---
abstract: 'provide a version number by bumping the last git release tag'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-BumpVersionFromGit
no_index:
  directory:
    - t
    - xt
    - examples
provides:
  Dist::Zilla::Plugin::BumpVersionFromGit:
    file: lib/Dist/Zilla/Plugin/BumpVersionFromGit.pm
    version: 0.003
requires:
  Dist::Zilla: 1.100711
  Dist::Zilla::Role::VersionProvider: 1.100711
  Git::Wrapper: 0.007
  Moose: 0.990
  Path::Class: 0.170
  Test::Exception: 0.290
  Test::More: 0.88
  Version::Next: 0.001
  namespace::autoclean: 0.090
  version: 0.800
resources:
  repository: http://github.com/dagolden/dist-zilla-plugin-bumpversionfromgit
version: 0.003
